version: "3"

services:
  drone:
    image: "drone/drone:1.0.0-rc.3"
    restart: "always"
    environment:
      DRONE_SERVER_PROTO: "https"
      DRONE_RUNNER_CAPACITY: 2
      DRONE_TLS_AUTOCERT: "true"
      DRONE_TIMEOUT: "24h"
    env_file:
      - drone_config.env
    ports:
      - "8080:80"
    volumes:
      - "./dev/drone:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
