version: "3"

services:
  drone:
    image: "drone/drone:1.0.0-rc.3"
    restart: "always"
    env_file: "drone_config.env"
    environment:
      DRONE_SERVER_PROTO: "http"
      DRONE_RUNNER_CAPACITY: 4
      DRONE_TIMEOUT: "24h"
      DRONE_CRON_INTERVAL: 30m
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./dev/drone:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
