version: "3"

services:
  drone:
    image: "drone/drone:1.0.0-rc.1"
    restart: "always"
    environment:
      DRONE_USER_FILTER: ${DRONE_USER_FILTER}
      DRONE_BITBUCKET_CLIENT_ID: ${DRONE_BITBUCKET_CLIENT_ID}
      DRONE_BITBUCKET_CLIENT_SECRET: ${DRONE_BITBUCKET_CLIENT_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: "https"
      DRONE_RUNNER_CAPACITY: 2
      DRONE_TLS_AUTOCERT: "false"
      DRONE_TIMEOUT: "24h"
    ports:
      - "8080:80"
    volumes:
      - "./dev/drone:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
